INSERT INTO atms.keyword (value) VALUES ('java');
INSERT INTO atms.keyword (value) VALUES ('oauth2');
INSERT INTO atms.keyword (value) VALUES ('dao');
INSERT INTO atms.keyword (value) VALUES ('rest');
INSERT INTO atms.keyword (value) VALUES ('security');
INSERT INTO atms.keyword (value) VALUES ('dbms');
INSERT INTO atms.keyword (value) VALUES ('mysql');
INSERT INTO atms.keyword (value) VALUES ('authorization');
INSERT INTO atms.keyword (value) VALUES ('storage');
INSERT INTO atms.keyword (value) VALUES ('files');
INSERT INTO atms.keyword (value) VALUES ('log');
INSERT INTO atms.keyword (value) VALUES ('document');
INSERT INTO atms.keyword (value) VALUES ('task');
INSERT INTO atms.keyword (value) VALUES ('management');
INSERT INTO atms.keyword (value) VALUES ('statistics');
INSERT INTO atms.keyword (value) VALUES ('data');
INSERT INTO atms.keyword (value) VALUES ('test');
INSERT INTO atms.keyword (value) VALUES ('social networks');
INSERT INTO atms.keyword (value) VALUES ('task description');
INSERT INTO atms.keyword (value) VALUES ('search');
INSERT INTO atms.keyword (value) VALUES ('task title');
INSERT INTO atms.keyword (value) VALUES ('email');
INSERT INTO atms.keyword (value) VALUES ('notifier');
INSERT INTO atms.keyword (value) VALUES ('dump');
INSERT INTO atms.keyword (value) VALUES ('user');
INSERT INTO atms.keyword (value) VALUES ('lock');
INSERT INTO atms.keyword (value) VALUES ('data model');
INSERT INTO atms.keyword (value) VALUES ('entities');
INSERT INTO atms.keyword (value) VALUES ('current');